server:
  port: 8081
  servlet:
    context-path: /vehicle-service

spring:
  application:
    name: vehicle-service


  datasource:
    url: jdbc:mysql://localhost:3306/smart_parking_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


#service eka register kara witharai