server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, Passed

      routes:
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parking-service/**


        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**


        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**


        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**


jwt:
  secret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566DF423F4428472B4B6250655368566D

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
