spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parking-service/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

jwt:
  secret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566DF423F4428472B4B6250655368566D

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
