spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parking-service/**

        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



#  http://localhost:8081/vehicle-service/api/v1/vehicle/all
#  http://localhost:8080/user-service/api/v1/user/all
#  http://localhost:8082/parking-service/api/v1/parking/all
#  http://localhost:8083/payment-service/api/v1/payment/all