server:
  port: 8082
  servlet:
    context-path: /parking-service

spring:
  application:
    name: parking-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#service eka rejister kara witharai